/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayStealBrainrotRouteImport } from './routes/play.steal-brainrot'
import { Route as PlayRivalsRouteImport } from './routes/play.rivals'
import { Route as PlayObbyTowerRouteImport } from './routes/play.obby-tower'
import { Route as PlayObbySpeedRouteImport } from './routes/play.obby-speed'
import { Route as PlayObbySkyRouteImport } from './routes/play.obby-sky'
import { Route as PlayObbyNeonRouteImport } from './routes/play.obby-neon'
import { Route as PlayObbyLavaRouteImport } from './routes/play.obby-lava'
import { Route as PlayObbyJungleRouteImport } from './routes/play.obby-jungle'
import { Route as PlayObbyIceRouteImport } from './routes/play.obby-ice'
import { Route as PlayNaturalDisasterRouteImport } from './routes/play.natural-disaster'
import { Route as PlayGrowGardenRouteImport } from './routes/play.grow-garden'

const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayStealBrainrotRoute = PlayStealBrainrotRouteImport.update({
  id: '/play/steal-brainrot',
  path: '/play/steal-brainrot',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRivalsRoute = PlayRivalsRouteImport.update({
  id: '/play/rivals',
  path: '/play/rivals',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayObbyTowerRoute = PlayObbyTowerRouteImport.update({
  id: '/play/obby-tower',
  path: '/play/obby-tower',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayObbySpeedRoute = PlayObbySpeedRouteImport.update({
  id: '/play/obby-speed',
  path: '/play/obby-speed',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayObbySkyRoute = PlayObbySkyRouteImport.update({
  id: '/play/obby-sky',
  path: '/play/obby-sky',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayObbyNeonRoute = PlayObbyNeonRouteImport.update({
  id: '/play/obby-neon',
  path: '/play/obby-neon',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayObbyLavaRoute = PlayObbyLavaRouteImport.update({
  id: '/play/obby-lava',
  path: '/play/obby-lava',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayObbyJungleRoute = PlayObbyJungleRouteImport.update({
  id: '/play/obby-jungle',
  path: '/play/obby-jungle',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayObbyIceRoute = PlayObbyIceRouteImport.update({
  id: '/play/obby-ice',
  path: '/play/obby-ice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayNaturalDisasterRoute = PlayNaturalDisasterRouteImport.update({
  id: '/play/natural-disaster',
  path: '/play/natural-disaster',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGrowGardenRoute = PlayGrowGardenRouteImport.update({
  id: '/play/grow-garden',
  path: '/play/grow-garden',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/lobby': typeof LobbyRoute
  '/play/grow-garden': typeof PlayGrowGardenRoute
  '/play/natural-disaster': typeof PlayNaturalDisasterRoute
  '/play/obby-ice': typeof PlayObbyIceRoute
  '/play/obby-jungle': typeof PlayObbyJungleRoute
  '/play/obby-lava': typeof PlayObbyLavaRoute
  '/play/obby-neon': typeof PlayObbyNeonRoute
  '/play/obby-sky': typeof PlayObbySkyRoute
  '/play/obby-speed': typeof PlayObbySpeedRoute
  '/play/obby-tower': typeof PlayObbyTowerRoute
  '/play/rivals': typeof PlayRivalsRoute
  '/play/steal-brainrot': typeof PlayStealBrainrotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/lobby': typeof LobbyRoute
  '/play/grow-garden': typeof PlayGrowGardenRoute
  '/play/natural-disaster': typeof PlayNaturalDisasterRoute
  '/play/obby-ice': typeof PlayObbyIceRoute
  '/play/obby-jungle': typeof PlayObbyJungleRoute
  '/play/obby-lava': typeof PlayObbyLavaRoute
  '/play/obby-neon': typeof PlayObbyNeonRoute
  '/play/obby-sky': typeof PlayObbySkyRoute
  '/play/obby-speed': typeof PlayObbySpeedRoute
  '/play/obby-tower': typeof PlayObbyTowerRoute
  '/play/rivals': typeof PlayRivalsRoute
  '/play/steal-brainrot': typeof PlayStealBrainrotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/lobby': typeof LobbyRoute
  '/play/grow-garden': typeof PlayGrowGardenRoute
  '/play/natural-disaster': typeof PlayNaturalDisasterRoute
  '/play/obby-ice': typeof PlayObbyIceRoute
  '/play/obby-jungle': typeof PlayObbyJungleRoute
  '/play/obby-lava': typeof PlayObbyLavaRoute
  '/play/obby-neon': typeof PlayObbyNeonRoute
  '/play/obby-sky': typeof PlayObbySkyRoute
  '/play/obby-speed': typeof PlayObbySpeedRoute
  '/play/obby-tower': typeof PlayObbyTowerRoute
  '/play/rivals': typeof PlayRivalsRoute
  '/play/steal-brainrot': typeof PlayStealBrainrotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avatar'
    | '/lobby'
    | '/play/grow-garden'
    | '/play/natural-disaster'
    | '/play/obby-ice'
    | '/play/obby-jungle'
    | '/play/obby-lava'
    | '/play/obby-neon'
    | '/play/obby-sky'
    | '/play/obby-speed'
    | '/play/obby-tower'
    | '/play/rivals'
    | '/play/steal-brainrot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avatar'
    | '/lobby'
    | '/play/grow-garden'
    | '/play/natural-disaster'
    | '/play/obby-ice'
    | '/play/obby-jungle'
    | '/play/obby-lava'
    | '/play/obby-neon'
    | '/play/obby-sky'
    | '/play/obby-speed'
    | '/play/obby-tower'
    | '/play/rivals'
    | '/play/steal-brainrot'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/avatar'
    | '/lobby'
    | '/play/grow-garden'
    | '/play/natural-disaster'
    | '/play/obby-ice'
    | '/play/obby-jungle'
    | '/play/obby-lava'
    | '/play/obby-neon'
    | '/play/obby-sky'
    | '/play/obby-speed'
    | '/play/obby-tower'
    | '/play/rivals'
    | '/play/steal-brainrot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AvatarRoute: typeof AvatarRoute
  LobbyRoute: typeof LobbyRoute
  PlayGrowGardenRoute: typeof PlayGrowGardenRoute
  PlayNaturalDisasterRoute: typeof PlayNaturalDisasterRoute
  PlayObbyIceRoute: typeof PlayObbyIceRoute
  PlayObbyJungleRoute: typeof PlayObbyJungleRoute
  PlayObbyLavaRoute: typeof PlayObbyLavaRoute
  PlayObbyNeonRoute: typeof PlayObbyNeonRoute
  PlayObbySkyRoute: typeof PlayObbySkyRoute
  PlayObbySpeedRoute: typeof PlayObbySpeedRoute
  PlayObbyTowerRoute: typeof PlayObbyTowerRoute
  PlayRivalsRoute: typeof PlayRivalsRoute
  PlayStealBrainrotRoute: typeof PlayStealBrainrotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/steal-brainrot': {
      id: '/play/steal-brainrot'
      path: '/play/steal-brainrot'
      fullPath: '/play/steal-brainrot'
      preLoaderRoute: typeof PlayStealBrainrotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/rivals': {
      id: '/play/rivals'
      path: '/play/rivals'
      fullPath: '/play/rivals'
      preLoaderRoute: typeof PlayRivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/obby-tower': {
      id: '/play/obby-tower'
      path: '/play/obby-tower'
      fullPath: '/play/obby-tower'
      preLoaderRoute: typeof PlayObbyTowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/obby-speed': {
      id: '/play/obby-speed'
      path: '/play/obby-speed'
      fullPath: '/play/obby-speed'
      preLoaderRoute: typeof PlayObbySpeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/obby-sky': {
      id: '/play/obby-sky'
      path: '/play/obby-sky'
      fullPath: '/play/obby-sky'
      preLoaderRoute: typeof PlayObbySkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/obby-neon': {
      id: '/play/obby-neon'
      path: '/play/obby-neon'
      fullPath: '/play/obby-neon'
      preLoaderRoute: typeof PlayObbyNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/obby-lava': {
      id: '/play/obby-lava'
      path: '/play/obby-lava'
      fullPath: '/play/obby-lava'
      preLoaderRoute: typeof PlayObbyLavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/obby-jungle': {
      id: '/play/obby-jungle'
      path: '/play/obby-jungle'
      fullPath: '/play/obby-jungle'
      preLoaderRoute: typeof PlayObbyJungleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/obby-ice': {
      id: '/play/obby-ice'
      path: '/play/obby-ice'
      fullPath: '/play/obby-ice'
      preLoaderRoute: typeof PlayObbyIceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/natural-disaster': {
      id: '/play/natural-disaster'
      path: '/play/natural-disaster'
      fullPath: '/play/natural-disaster'
      preLoaderRoute: typeof PlayNaturalDisasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/grow-garden': {
      id: '/play/grow-garden'
      path: '/play/grow-garden'
      fullPath: '/play/grow-garden'
      preLoaderRoute: typeof PlayGrowGardenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AvatarRoute: AvatarRoute,
  LobbyRoute: LobbyRoute,
  PlayGrowGardenRoute: PlayGrowGardenRoute,
  PlayNaturalDisasterRoute: PlayNaturalDisasterRoute,
  PlayObbyIceRoute: PlayObbyIceRoute,
  PlayObbyJungleRoute: PlayObbyJungleRoute,
  PlayObbyLavaRoute: PlayObbyLavaRoute,
  PlayObbyNeonRoute: PlayObbyNeonRoute,
  PlayObbySkyRoute: PlayObbySkyRoute,
  PlayObbySpeedRoute: PlayObbySpeedRoute,
  PlayObbyTowerRoute: PlayObbyTowerRoute,
  PlayRivalsRoute: PlayRivalsRoute,
  PlayStealBrainrotRoute: PlayStealBrainrotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
