/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayStealBrainrotRouteImport } from './routes/play.steal-brainrot'
import { Route as PlayRivalsRouteImport } from './routes/play.rivals'
import { Route as PlayObbyTowerRouteImport } from './routes/play.obby-tower'
import { Route as PlayObbySpeedRouteImport } from './routes/play.obby-speed'
import { Route as PlayNaturalDisasterRouteImport } from './routes/play.natural-disaster'
import { Route as PlayGrowGardenRouteImport } from './routes/play.grow-garden'

const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayStealBrainrotRoute = PlayStealBrainrotRouteImport.update({
  id: '/play/steal-brainrot',
  path: '/play/steal-brainrot',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRivalsRoute = PlayRivalsRouteImport.update({
  id: '/play/rivals',
  path: '/play/rivals',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayObbyTowerRoute = PlayObbyTowerRouteImport.update({
  id: '/play/obby-tower',
  path: '/play/obby-tower',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayObbySpeedRoute = PlayObbySpeedRouteImport.update({
  id: '/play/obby-speed',
  path: '/play/obby-speed',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayNaturalDisasterRoute = PlayNaturalDisasterRouteImport.update({
  id: '/play/natural-disaster',
  path: '/play/natural-disaster',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGrowGardenRoute = PlayGrowGardenRouteImport.update({
  id: '/play/grow-garden',
  path: '/play/grow-garden',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/lobby': typeof LobbyRoute
  '/play/grow-garden': typeof PlayGrowGardenRoute
  '/play/natural-disaster': typeof PlayNaturalDisasterRoute
  '/play/obby-speed': typeof PlayObbySpeedRoute
  '/play/obby-tower': typeof PlayObbyTowerRoute
  '/play/rivals': typeof PlayRivalsRoute
  '/play/steal-brainrot': typeof PlayStealBrainrotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/lobby': typeof LobbyRoute
  '/play/grow-garden': typeof PlayGrowGardenRoute
  '/play/natural-disaster': typeof PlayNaturalDisasterRoute
  '/play/obby-speed': typeof PlayObbySpeedRoute
  '/play/obby-tower': typeof PlayObbyTowerRoute
  '/play/rivals': typeof PlayRivalsRoute
  '/play/steal-brainrot': typeof PlayStealBrainrotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/lobby': typeof LobbyRoute
  '/play/grow-garden': typeof PlayGrowGardenRoute
  '/play/natural-disaster': typeof PlayNaturalDisasterRoute
  '/play/obby-speed': typeof PlayObbySpeedRoute
  '/play/obby-tower': typeof PlayObbyTowerRoute
  '/play/rivals': typeof PlayRivalsRoute
  '/play/steal-brainrot': typeof PlayStealBrainrotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avatar'
    | '/lobby'
    | '/play/grow-garden'
    | '/play/natural-disaster'
    | '/play/obby-speed'
    | '/play/obby-tower'
    | '/play/rivals'
    | '/play/steal-brainrot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avatar'
    | '/lobby'
    | '/play/grow-garden'
    | '/play/natural-disaster'
    | '/play/obby-speed'
    | '/play/obby-tower'
    | '/play/rivals'
    | '/play/steal-brainrot'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/avatar'
    | '/lobby'
    | '/play/grow-garden'
    | '/play/natural-disaster'
    | '/play/obby-speed'
    | '/play/obby-tower'
    | '/play/rivals'
    | '/play/steal-brainrot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AvatarRoute: typeof AvatarRoute
  LobbyRoute: typeof LobbyRoute
  PlayGrowGardenRoute: typeof PlayGrowGardenRoute
  PlayNaturalDisasterRoute: typeof PlayNaturalDisasterRoute
  PlayObbySpeedRoute: typeof PlayObbySpeedRoute
  PlayObbyTowerRoute: typeof PlayObbyTowerRoute
  PlayRivalsRoute: typeof PlayRivalsRoute
  PlayStealBrainrotRoute: typeof PlayStealBrainrotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/steal-brainrot': {
      id: '/play/steal-brainrot'
      path: '/play/steal-brainrot'
      fullPath: '/play/steal-brainrot'
      preLoaderRoute: typeof PlayStealBrainrotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/rivals': {
      id: '/play/rivals'
      path: '/play/rivals'
      fullPath: '/play/rivals'
      preLoaderRoute: typeof PlayRivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/obby-tower': {
      id: '/play/obby-tower'
      path: '/play/obby-tower'
      fullPath: '/play/obby-tower'
      preLoaderRoute: typeof PlayObbyTowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/obby-speed': {
      id: '/play/obby-speed'
      path: '/play/obby-speed'
      fullPath: '/play/obby-speed'
      preLoaderRoute: typeof PlayObbySpeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/natural-disaster': {
      id: '/play/natural-disaster'
      path: '/play/natural-disaster'
      fullPath: '/play/natural-disaster'
      preLoaderRoute: typeof PlayNaturalDisasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/grow-garden': {
      id: '/play/grow-garden'
      path: '/play/grow-garden'
      fullPath: '/play/grow-garden'
      preLoaderRoute: typeof PlayGrowGardenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AvatarRoute: AvatarRoute,
  LobbyRoute: LobbyRoute,
  PlayGrowGardenRoute: PlayGrowGardenRoute,
  PlayNaturalDisasterRoute: PlayNaturalDisasterRoute,
  PlayObbySpeedRoute: PlayObbySpeedRoute,
  PlayObbyTowerRoute: PlayObbyTowerRoute,
  PlayRivalsRoute: PlayRivalsRoute,
  PlayStealBrainrotRoute: PlayStealBrainrotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
